version: '3.3'

services:
  app:
    build:
      context: .
    networks:
      - mynet
    restart: always
    volumes:
      - .:/var/www/application
    ports:
      - '1212:80'

  db:
    image: mysql:5.7
    networks:
      - mynet
    restart: always
    environment:
      MYSQL_DATABASE: 'dataak'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user@password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root@password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3398:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:

networks:
  mynet: